name: flutter_deer web deploy

# push 提交中修改`pubspec.yaml`触发此workflow。
# 为了避免每次部署，这里使用一个不存在的文件名。
on:
  push:
    paths:
      - 'pubspec1.yaml'

jobs:
  web_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.0'
          channel: 'stable'
      - name: "Web Build 🔧"
        run: |
          flutter pub get
          flutter build web
      - name: Deploy Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:flutter-webhost
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            PROJECT_PATH: ./build/web
